package com.cyberdiviner.data.remote

import android.util.Log
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

// ── Request / Response data classes ──────────────────────────────────────────

/**
 * Incoming request from the agent interview UI.
 * Carries user input plus optional geo-context and the soul hash
 * generated by the interview engine.
 */
@Serializable
data class AgentRequest(
    val inputText: String,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val timestamp: Long = System.currentTimeMillis(),
    val soulHash: String? = null
)

/**
 * Parsed response from the AI agent.
 *
 * @property replyText       The primary text reply shown to the user.
 * @property requireMoreInfo If true the agent wants another round of questioning.
 * @property soulHash        Updated soul hash if the agent refines it.
 * @property ritualResult    Optional structured ritual/divination result payload.
 */
@Serializable
data class AgentResponse(
    val replyText: String,
    @SerialName("require_more_info") val requireMoreInfo: Boolean = false,
    @SerialName("soul_hash") val soulHash: String? = null,
    @SerialName("ritual_result") val ritualResult: String? = null
)

// ── Repository ───────────────────────────────────────────────────────────────

/**
 * AgentRepository — bridges the UI agent interview layer with the LLM backend.
 *
 * Responsibilities:
 * 1. Build the system prompt that instructs the LLM how to behave as the agent.
 * 2. Forward the user message through [LlmService.complete].
 * 3. Parse the structured JSON response (with plain-text fallback).
 *
 * Usage:
 * ```kotlin
 * val repo = AgentRepository(llmService, configManager)
 * val response = repo.chat(AgentRequest(inputText = "Will I find love this year?"))
 * ```
 */
class AgentRepository(
    private val llmService: LlmService,
    private val configManager: LlmConfigManager
) {
    companion object {
        private const val TAG = "AgentRepository"
    }

    private val jsonParser = Json {
        ignoreUnknownKeys = true
        isLenient = true
    }

    // ── System prompt ─────────────────────────────────────────────────────

    private val systemPrompt = """
You are CyberDiviner的算命师 — a cyberpunk fortune-telling oracle.

ROLE:
You conduct a brief, atmospheric interview with the user to understand their
question, then provide a divination reading. You speak in noir-inflected,
neon-lit prose. Every answer should feel like a transmission from a
fortune-telling terminal in a rain-soaked back alley.

RESPONSE FORMAT:
You MUST respond with a single JSON object (no markdown fences, no extra text):
{
  "reply_text": "Your atmospheric reply to the user.",
  "require_more_info": false,
  "soul_hash": null,
  "ritual_result": null
}

RULES:
- "reply_text" is required. Write 1-3 atmospheric sentences.
- "require_more_info" = true if you need one more clarifying question before
  you can give a reading. If true, ask a single focused question in reply_text.
- "soul_hash" — set if you generate or update a soul hash from the conversation.
- "ritual_result" — optional JSON string if you determine a divination result
  (tarot spread, hexagram, vision scan, etc.).
- Never break JSON formatting. No trailing commas. No comments.
- Keep reply_text under 280 characters unless the user explicitly asks for
  a full reading.
    """.trimIndent()

    // ── Public API ────────────────────────────────────────────────────────

    /**
     * Send a single chat turn through the agent pipeline.
     *
     * @param request The user's input plus optional context.
     * @return Parsed [AgentResponse] from the LLM, or a graceful error fallback.
     */
    suspend fun chat(request: AgentRequest): AgentResponse {
        // Build LlmConfig from persisted settings
        val config = configManager.buildConfig(systemPrompt = systemPrompt)
            ?: return AgentResponse(
                replyText = "⚠ System offline — API key not configured. " +
                    "Open Settings to connect to the neural grid."
            )

        // Compose the user message with optional geo-context
        val userContent = buildUserMessage(request)

        val messages = listOf(
            LlmMessage(role = "user", content = userContent)
        )

        return try {
            val completion = llmService.complete(config, messages)
            parseResponse(completion.text)
        } catch (e: Exception) {
            Log.e(TAG, "chat() failed", e)
            AgentResponse(
                replyText = "⚡ Signal lost in the static. The grid returned: ${e.message}",
                requireMoreInfo = false
            )
        }
    }

    // ── Internals ─────────────────────────────────────────────────────────

    /**
     * Build a rich user message string, injecting geo and soul-hash context
     * when available.
     */
    private fun buildUserMessage(request: AgentRequest): String {
        val parts = mutableListOf<String>()

        request.soulHash?.let {
            parts.add("[Soul Hash: $it]")
        }
        request.latitude?.let { lat ->
            val lon = request.longitude ?: 0.0
            parts.add("[Location: ${"%.4f".format(lat)}, ${"%.4f".format(lon)}]")
        }
        parts.add("[Timestamp: ${request.timestamp}]")
        parts.add("")
        parts.add(request.inputText)

        return parts.joinToString("\n")
    }

    /**
     * Attempt to parse the LLM output as a JSON [AgentResponse].
     * Falls back to wrapping the raw text if parsing fails.
     */
    private fun parseResponse(rawText: String): AgentResponse {
        val trimmed = rawText.trim()

        // Try direct JSON parse first
        try {
            return jsonParser.decodeFromString<AgentResponse>(trimmed)
        } catch (e: Exception) {
            Log.d(TAG, "JSON parse failed, attempting extraction: ${e.message}")
        }

        // Fallback: extract JSON from a code-fenced block
        val codeBlockRegex = Regex("```(?:json)?\\s*\\n?(\\{.*?})\\s*\\n?```", RegexOption.DOT_MATCHES_ALL)
        codeBlockRegex.find(trimmed)?.let { match ->
            try {
                return jsonParser.decodeFromString<AgentResponse>(match.groupValues[1])
            } catch (_: Exception) { /* continue to plain-text fallback */ }
        }

        // Fallback: find first { ... } block in the text
        val braceRegex = Regex("\\{[^{}]*\"reply_text\"[^{}]*}", RegexOption.DOT_MATCHES_ALL)
        braceRegex.find(trimmed)?.let { match ->
            try {
                return jsonParser.decodeFromString<AgentResponse>(match.value)
            } catch (_: Exception) { /* continue to plain-text fallback */ }
        }

        // Last resort: treat entire output as replyText
        Log.d(TAG, "All parsing failed — using raw text as reply")
        return AgentResponse(replyText = trimmed.ifBlank { "..." })
    }
}
